module.exports = [
    { href: '/generate', name: 'GENERATE' },
    { href: '/escape', name: 'ESCAPE' },
    // { href: '/restful-valid/restful-valid', name: 'JSON校验' },
    { href: '/json-tool', name: 'JSON TOOL' },
    // { href: '/test/bodymovin', name: 'BODY MOVIN' },
    // { href: '/test/view-log', name: 'VIEW LOG' },
    // { href: '/game/five-in-a-row', name: '五子棋' },
    // { href: '/test/star-wars', name: 'STAR WARS' },
    { href: '/regexp-doc', name: '正则表达式全部符号解释' },
    { href: '/chart', name: '图表' },
    { href: '/gnuplot', name: 'Gnuplot' },
    { href: '/test/three.js/particle/fireworks', name: '3DFireWorks' },
    // { href: '/game/maze', name: '迷宫' },
    { href: '/editor/editor', name: 'EDITOR' },
    { href: '/editor/diff-editor', name: 'DIFF EDITOR' },
]
