module.exports = [
    { href: '/src/gen/gen.html', name: 'GENERATE' },
    { href: '/src/escape/escape.html', name: 'ESCAPE' },
    { href: '/src/restful-valid/restful-valid.html', name: 'JSON校验' },
    { href: '/src/json-tool/json-tool.html', name: 'JSON TOOL' },
    { href: '/src/test/bodymovin.html', name: 'BODY MOVIN' },
    { href: '/src/test/view-log.html', name: 'VIEW LOG' },
    { href: '/src/game/five-in-a-row.html', name: '五子棋' },
    { href: '/src/test/star-wars.html', name: 'STAR WARS' },
    { href: '/src/test/regexp.html', name: '正则表达式全部符号解释' },
    { href: '/src/chart/chart.html', name: '图表' },
    { href: '/src/gnuplot/gnuplot.html', name: 'Gnuplot' },
    { href: '/src/test/three.js/particle/fireworks.html', name: '3DFireWorks' },
    { href: '/src/game/maze.html', name: '迷宫' },
    { href: '/src/editor/editor.html', name: 'EDITOR' },
    { href: '/src/editor/diff-editor.html', name: 'DIFF EDITOR' },
]
