var getPath = function (path) {
  var url = document.location.href;
  return url.substr(0, url.indexOf('src')) + path;
}

var loadJsConfig = {
  "jquery":[
    "https://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"
  ],
  "jqueryui":[
    "https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.structure.min.css",
    "https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.theme.min.css",
    "https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.js",
    "https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.css"
  ],
  "mark":[
    "https://cdn.bootcss.com/mark.js/8.9.0/mark.min.js",
    "https://cdn.bootcss.com/mark.js/8.9.0/jquery.mark.min.js"
  ],
  "tether":[
    "https://cdn.bootcss.com/tether/1.4.0/css/tether.min.css",
    "https://cdn.bootcss.com/tether/1.4.0/js/tether.min.js"
  ],
  "bootstrap":[
    "https://cdn.bootcss.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css",
    "https://cdn.bootcss.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
  ],
  "bootstrap-css":[
    "https://cdn.bootcss.com/tether/1.4.0/css/tether.min.css",
    "https://cdn.bootcss.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
  ],
  "fontawesome":[
    "https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css"
  ],
  "three.js":[
    "https://cdn.bootcss.com/three.js/r83/three.min.js"
  ],
  "Stats":[
    "https://cdn.bootcss.com/stats.js/r16/Stats.min.js"
  ],
  "bodymovin":[
    "https://cdn.bootcss.com/bodymovin/4.5.8/bodymovin.js"
  ],
  "csshake":[
    "https://cdn.bootcss.com/csshake/1.5.1/csshake.min.css"
  ],
  "beautify":[
    "https://cdn.bootcss.com/js-beautify/1.6.12/beautify.min.js"
  ],
  "highlight":[
    getPath("highlight/styles/default.css"),
    getPath("highlight/highlight.pack.js")
  ],
  "string-format":[
    "https://cdn.bootcss.com/string-format/0.5.0/string-format.min.js"
  ],
  "escapes":[
    getPath("src/js/escape/MD5.js"),
    getPath("src/js/escape/Base64.js"),
    getPath("src/js/escape/he.js"),
    getPath("src/js/escape/crypto-js.js"),
    getPath("src/js/escape/escape.js")
  ],
  "java-model":[
    getPath("src/js/java-model/Modifiers.js"),
    getPath("src/js/java-model/Filed.js"),
    getPath("src/js/java-model/ClassModel.js")
  ],
  "common-utils":[
    getPath("src/js/utils/PageState.js")
  ],
  "gen-java":[
    getPath("src/js/gen-java/Fileds2Java.js"),
    getPath("src/js/gen-java/Json2Java.js"),
    getPath("src/js/gen-java/GenXML.js"),
    getPath("src/js/gen-java/GenJavaTemplate.js"),
    getPath("src/js/gen-java/SQL2Java.js")
  ],
  "normal-list":[
    getPath("src/js/list/normal-list.js")
  ],
  "fast-list":[
    getPath("src/js/list/fast-list.js")
  ],
  "wilddog":[
    "https://cdn.wilddog.com/sdk/js/2.3.10/wilddog.js"
  ],
  "wilddog-config":[
    getPath("src/js/utils/wilddog-config.js")
  ],
  "pako":[
    "https://cdn.bootcss.com/pako/1.0.5/pako.min.js"
  ],
  "wlog":[
    getPath("src/js/utils/wlog.js")
  ]
};
