if (typeof LoadES6 == 'undefined') {
  LoadES6 = {}
  LoadES6.config = Load.config
}

LoadES6.config({
  "jquery":[
    "https://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"
  ],
  "jqueryui":[
    "https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.structure.min.css",
    "https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.theme.min.css",
    "https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.js",
    "https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.css"
  ],
  "jquery.qrcode":[
    "https://cdn.bootcss.com/jquery.qrcode/1.0/jquery.qrcode.min.js"
  ],
  "JsBarcode":[
    "https://cdn.bootcss.com/jsbarcode/3.6.0/JsBarcode.all.min.js"
  ],
  "jquery-terminal":[
    "https://cdn.bootcss.com/jquery.terminal/1.4.0/css/jquery.terminal.min.css",
    "https://cdn.bootcss.com/jquery.terminal/1.4.0/js/jquery.terminal.min.js"
  ],
  "codemirror":[
    "https://cdn.bootcss.com/codemirror/5.25.2/codemirror.min.js",
    "https://cdn.bootcss.com/codemirror/5.25.2/theme/dracula.min.css",
    "https://cdn.bootcss.com/codemirror/5.25.2/codemirror.min.css"
  ],
  "codemirror-show-hint":[
    "https://cdn.bootcss.com/codemirror/5.25.2/addon/hint/show-hint.min.css",
    "https://cdn.bootcss.com/codemirror/5.25.2/addon/hint/show-hint.min.js"
  ],
  "codemirror-javascript":[
    "https://cdn.bootcss.com/codemirror/5.25.2/addon/hint/javascript-hint.min.js",
    "https://cdn.bootcss.com/codemirror/5.25.2/addon/lint/javascript-lint.min.js",
    "https://cdn.bootcss.com/codemirror/5.25.2/mode/javascript/javascript.min.js"
  ],
  "mark":[
    "https://cdn.bootcss.com/mark.js/8.9.0/mark.min.js",
    "https://cdn.bootcss.com/mark.js/8.9.0/jquery.mark.min.js"
  ],
  "tether":[
    "https://cdn.bootcss.com/tether/1.4.0/css/tether.min.css",
    "https://cdn.bootcss.com/tether/1.4.0/js/tether.min.js"
  ],
  "popper":[
    "https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"
  ],
  "bootstrap":[
    "https://cdn.bootcss.com/bootstrap/4.0.0-beta/css/bootstrap.min.css",
    "https://cdn.bootcss.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
  ],
  "bootstrap-css":[
    "https://cdn.bootcss.com/tether/1.4.0/css/tether.min.css",
    "https://cdn.bootcss.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
  ],
  "jade":[
    "https://cdn.bootcss.com/jade/1.11.0/jade.min.js"
  ],
  "bootstrap-table":[
    "https://cdn.bootcss.com/bootstrap-table/1.11.1/bootstrap-table.min.js",
    "https://cdn.bootcss.com/bootstrap-table/1.11.1/bootstrap-table.min.css"
  ],
  "fontawesome":[
    "https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css"
  ],
  "three.js":[
    "https://cdn.bootcss.com/three.js/r83/three.min.js"
  ],
  "Stats":[
    "https://cdn.bootcss.com/stats.js/r16/Stats.min.js"
  ],
  "particles":[
    "https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"
  ],
  "bodymovin":[
    "https://cdn.bootcss.com/bodymovin/4.5.8/bodymovin.js"
  ],
  "csshake":[
    "https://cdn.bootcss.com/csshake/1.5.2/csshake.min.css"
  ],
  "beautify":[
    "https://cdn.bootcss.com/js-beautify/1.6.12/beautify.min.js"
  ],
  "highlight":[
    "https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js",
    "https://cdn.bootcss.com/highlight.js/9.12.0/styles/atom-one-light.min.css"
  ],
  "highlight-languages":[
    "https://cdn.bootcss.com/highlight.js/9.12.0/languages/javascript.min.js",
    "https://cdn.bootcss.com/highlight.js/9.12.0/languages/xml.min.js",
    "https://cdn.bootcss.com/highlight.js/9.12.0/languages/json.min.js"
  ],
  "string-format":[
    "https://cdn.bootcss.com/string-format/0.5.0/string-format.min.js"
  ],
  "chart":[
    // "https://cdn.bootcss.com/Chart.js/2.6.0/Chart.min.js",
    // "https://cdn.bootcss.com/Chart.js/2.6.0/Chart.bundle.min.js"
    "https://cdn.bootcss.com/Chart.js/2.6.0/Chart.js",
    "https://cdn.bootcss.com/Chart.js/2.6.0/Chart.bundle.js"
  ],
  "sql":[
    "https://cdn.bootcss.com/sql.js/0.4.0/js/sql.js"
  ],
  "jszip":[
    "https://cdn.bootcss.com/jszip/3.1.4/jszip.js"
  ],
  "goldenlayout":[
    "https://cdn.bootcss.com/golden-layout/1.5.9/css/goldenlayout-base.css",
    "https://cdn.bootcss.com/golden-layout/1.5.9/css/goldenlayout-light-theme.css",
    // "https://cdn.bootcss.com/golden-layout/1.5.9/css/goldenlayout-dark-theme.css",
    // "https://cdn.bootcss.com/golden-layout/1.5.9/css/default-theme.css",
    // "https://cdn.bootcss.com/golden-layout/1.5.9/css/goldenlayout-soda-theme.css",
    // "https://cdn.bootcss.com/golden-layout/1.5.9/css/goldenlayout-translucent-theme.css",
    "https://cdn.bootcss.com/golden-layout/1.5.9/goldenlayout.min.js"
  ],
  "escapes":[
    "/src/js/escape/MD5.js",
    "/src/js/escape/Base64.js",
    "/src/js/escape/he.js",
    "/src/js/escape/crypto-js.js",
    "/src/js/escape/escape.js"
  ],
  "java-model":[
    "/src/js/java-model/Modifiers.js",
    "/src/js/java-model/Filed.js",
    "/src/js/java-model/ClassModel.js"
  ],
  "common-utils":[
    "/src/js/utils/PageState.js"
  ],
  "gen-java":[
    "/src/js/gen-java/Fileds2Java.js",
    "/src/js/gen-java/Json2Java.js",
    "/src/js/gen-java/GenXML.js",
    "/src/js/gen-java/GenJavaTemplate.js",
    "/src/js/gen-java/SQL2Java.js"
  ],
  "normal-list":[
    "/src/js/list/normal-list.js"
  ],
  "fast-list":[
    "/src/js/list/fast-list.js"
  ],
  "wilddog":[
    "https://cdn.wilddog.com/sdk/js/2.5.6/wilddog.js"
  ],
  "wilddog-config":[
    "/src/js/utils/wilddog-config.js"
  ],
  "pako":[
    "https://cdn.bootcss.com/pako/1.0.5/pako.min.js"
  ],
  "wlog":[
    "/src/js/utils/wlog.js"
  ]
});
