import Escape from './escape-api'

export default [
    { name: 'URL编码', handle: (text)=>({outputType:'javascript', output: encodeURIComponent(text)}) },
    { name: 'URL解码', handle: (text)=>({outputType:'javascript', output: decodeURIComponent(text)}) },
    { name: 'Base64编码', handle: (text)=>({outputType:'javascript', output: Escape.encodeBase64(text)}) },
    { name: 'Base64解码', handle: (text)=>({outputType:'javascript', output: Escape.decodeBase64(text)}) },
    { name: 'Html编码', handle: (text)=>({outputType:'javascript', output: Escape.htmlEncode(text)}) },
    { name: 'Html解码', handle: (text)=>({outputType:'javascript', output: Escape.htmlDecode(text)}) },
    { name: 'GZIP编码', handle: (text)=>({outputType:'javascript', output: Escape.encodeGZIP(text)}) },
    { name: 'GZIP解码', handle: (text)=>({outputType:'javascript', output: Escape.decodeGZIP(text)}) },
    { name: 'ZIP编码', handle: (text)=>({outputType:'javascript', output: Escape.encodeZIP(text)}) },
    { name: 'ZIP解码', handle: (text)=>({outputType:'javascript', output: Escape.decodeZIP(text)}) },
    { name: 'native2ascii', handle: (text)=>({outputType:'javascript', output: Escape.native2ascii(text)}) },
    { name: 'ascii2native', handle: (text)=>({outputType:'javascript', output: Escape.ascii2native(text)}) },
    { name: 'HtmlEncode', handle: (text)=>({outputType:'javascript', output: Escape.htmlEncode(text)}) },
    { name: 'HtmlDecode', handle: (text)=>({outputType:'javascript', output: Escape.htmlDecode(text)}) },
    { name: 'MD5', handle: (text)=>({outputType:'javascript', output: Escape.md5(text)}) },
    { name: 'SHA1', handle: (text)=>({outputType:'javascript', output: Escape.sha1(text)}) },
    { name: 'SHA256', handle: (text)=>({outputType:'javascript', output: Escape.sha256(text)}) },
    { name: 'SHA512', handle: (text)=>({outputType:'javascript', output: Escape.sha512(text)}) },
    { name: '格式化日期', handle: (text)=>({outputType:'javascript', output: Escape.formatDate(text)}) },
    { name: 'UNICODE编码', handle: (text)=>({outputType:'javascript', output: Escape.toUnicode(text)}) },
    { name: 'UNICODE解码', handle: (text)=>({outputType:'javascript', output: Escape.fromUnicode(text)}) },
    { name: '二维码', handle: async(text)=>({outputType:'img', img: await Escape.qrCode(text)}) },
    { name: '条形码', handle: async(text)=>({outputType:'img', img: await Escape.barCode(text)}) },
    { name: 'Base64IMG', handle: (text)=>({outputType:'img', img: Escape.base64img(text)}) },
    { name: 'JSON格式化', handle: (text)=>({outputType:'javascript', output: Escape.formatJSON(text)}) },
    { name: 'XML格式化', handle: (text)=>({outputType:'xml', output: Escape.formatXML(text)}) },
    { name: 'SQL格式化', handle: (text)=>({outputType:'sql', output: Escape.formatSQL(text)}) },
]